/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/api/v1/auth/me/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Профиль текущего пользователя: чтение и частичное обновление. */
    get: operations["auth_me_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    /** @description Профиль текущего пользователя: чтение и частичное обновление. */
    patch: operations["auth_me_partial_update"];
    trace?: never;
  };
  "/api/v1/auth/password/change/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Смена пароля: требует текущий пароль. */
    post: operations["auth_password_change_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/reset/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Запрос сброса пароля: шлёт письмо со ссылкой.
     *     Ответ всегда одинаковый — существование email не раскрываем.
     */
    post: operations["auth_password_reset_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/password/reset/confirm/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Установка нового пароля по ссылке из письма. */
    post: operations["auth_password_reset_confirm_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/register/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Регистрация: создаёт пользователя и сразу выдаёт пару токенов (автологин). */
    post: operations["auth_register_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/token/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Takes a set of user credentials and returns an access and refresh JSON web
     *     token pair to prove the authentication of those credentials.
     */
    post: operations["auth_token_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/auth/token/refresh/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * @description Takes a refresh type JSON web token and returns an access type JSON web
     *     token if the refresh token is valid.
     */
    post: operations["auth_token_refresh_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Список категорий и категория по слагу. */
    get: operations["categories_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/categories/{slug}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Список категорий и категория по слагу. */
    get: operations["categories_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/health/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Lightweight liveness probe used to verify the API is up. */
    get: operations["health_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /** @description Оформление заказа (гостевой чекаут) + история своих заказов. */
    post: operations["orders_create"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/orders/my/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Заказы текущего пользователя (только свои). */
    get: operations["orders_my_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Каталог: список товаров (с фильтрами) и карточка по слагу. */
    get: operations["products_list"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/v1/products/{slug}/": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** @description Каталог: список товаров (с фильтрами) и карточка по слагу. */
    get: operations["products_retrieve"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    AttributeValue: {
      readonly id: number;
      readonly attribute: string;
      readonly attribute_slug: string;
      /** Значение */
      value: string;
      /** Слаг */
      slug: string;
      /** Цвет (hex) */
      color_hex?: string;
    };
    /**
     * @description * `beige` - beige
     *     * `sage` - sage
     *     * `olive` - olive
     *     * `gray` - gray
     *     * `natural` - natural
     *     * `white` - white
     * @enum {string}
     */
    BagColorEnum: "beige" | "sage" | "olive" | "gray" | "natural" | "white";
    Category: {
      readonly id: number;
      /** Название */
      name: string;
      /** Слаг */
      slug: string;
      /** Родительская категория */
      parent?: number | null;
      /** Описание */
      description?: string;
    };
    /** @description Входные данные оформления заказа. Цены клиент не передаёт. */
    Checkout: {
      customer: components["schemas"]["Customer"];
      items: components["schemas"]["CheckoutItem"][];
    };
    CheckoutItem: {
      variant_id?: number;
      custom?: components["schemas"]["CustomConfig"];
      /** @default 1 */
      quantity: number;
    };
    /** @description Конфигурация конструктора; цена считается на сервере (pricing.py). */
    CustomConfig: {
      size: components["schemas"]["SizeEnum"];
      bag_color: components["schemas"]["BagColorEnum"];
      zipper_color: components["schemas"]["ZipperColorEnum"];
      /** @default false */
      tassel: boolean;
    };
    Customer: {
      name: string;
      phone: string;
      /** Format: email */
      email: string;
      /** @default  */
      comment: string;
    };
    Detail: {
      detail: string;
    };
    OrderItemRead: {
      /** Название */
      product_name: string;
      sku?: string;
      /**
       * Цена на момент покупки, ₽
       * Format: decimal
       */
      price: string;
      /** Количество */
      quantity?: number;
      /** Конфигурация конструктора */
      custom_config?: unknown;
      /** Format: decimal */
      readonly line_total: string;
    };
    OrderRead: {
      readonly id: number;
      /** Статус */
      status?: components["schemas"]["StatusEnum"];
      /** Статус оплаты */
      payment_status?: components["schemas"]["PaymentStatusEnum"];
      /** Имя */
      customer_name: string;
      /** Телефон */
      customer_phone: string;
      /**
       * Email
       * Format: email
       */
      customer_email: string;
      /** Комментарий (адрес, пожелания) */
      comment?: string;
      /**
       * Сумма, ₽
       * Format: decimal
       */
      total?: string;
      readonly items: components["schemas"]["OrderItemRead"][];
      /**
       * Создан
       * Format: date-time
       */
      readonly created_at: string;
    };
    PaginatedOrderReadList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["OrderRead"][];
    };
    PaginatedProductListList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["ProductList"][];
    };
    PasswordChange: {
      old_password: string;
      new_password: string;
    };
    PasswordReset: {
      /** Format: email */
      email: string;
    };
    PasswordResetConfirm: {
      uid: string;
      token: string;
      new_password: string;
    };
    /** @description PATCH /auth/me/: имя и телефон. */
    PatchedProfileUpdate: {
      first_name?: string;
      phone?: string;
    };
    /**
     * @description * `pending` - Ожидает оплаты
     *     * `paid` - Оплачен
     *     * `failed` - Ошибка оплаты
     * @enum {string}
     */
    PaymentStatusEnum: "pending" | "paid" | "failed";
    /** @description Full shape for the product page: description, gallery, variants, SEO. */
    ProductDetail: {
      readonly id: number;
      /** Название */
      name: string;
      /** Слаг */
      slug: string;
      readonly category: string;
      readonly category_name: string;
      readonly main_image: components["schemas"]["ProductImage"] | null;
      /** Format: decimal */
      readonly price_min: string;
      /** Format: decimal */
      readonly price_max: string;
      readonly in_stock: boolean;
      /** Описание */
      description?: string;
      readonly images: components["schemas"]["ProductImage"][];
      readonly variants: components["schemas"]["ProductVariant"][];
      meta_title?: string;
      meta_description?: string;
    };
    ProductImage: {
      readonly id: number;
      /**
       * Изображение
       * Format: uri
       */
      image: string;
      /** Alt-текст */
      alt_text?: string;
      /** Порядок */
      sort_order?: number;
      /** Главное */
      is_main?: boolean;
    };
    /** @description Lean shape for catalog grids: main image + price range, no heavy nesting. */
    ProductList: {
      readonly id: number;
      /** Название */
      name: string;
      /** Слаг */
      slug: string;
      readonly category: string;
      readonly category_name: string;
      readonly main_image: components["schemas"]["ProductImage"] | null;
      /** Format: decimal */
      readonly price_min: string;
      /** Format: decimal */
      readonly price_max: string;
      readonly in_stock: boolean;
    };
    ProductVariant: {
      readonly id: number;
      /** Артикул (SKU) */
      sku: string;
      /**
       * Цена, ₽
       * Format: decimal
       */
      price: string;
      /** Остаток */
      stock?: number;
      readonly in_stock: boolean;
      readonly attribute_values: components["schemas"]["AttributeValue"][];
    };
    /** @description Регистрация: email (= username), имя, телефон, пароль, согласие на ПДн. */
    Register: {
      /** Format: email */
      email: string;
      password: string;
      name: string;
      phone: string;
      consent: boolean;
    };
    /**
     * @description * `small` - small
     *     * `medium` - medium
     *     * `large` - large
     * @enum {string}
     */
    SizeEnum: "small" | "medium" | "large";
    /**
     * @description * `new` - Новый
     *     * `confirmed` - Подтверждён
     *     * `shipped` - Отправлен
     *     * `done` - Завершён
     *     * `cancelled` - Отменён
     * @enum {string}
     */
    StatusEnum: "new" | "confirmed" | "shipped" | "done" | "cancelled";
    TokenObtainPair: {
      username: string;
      password: string;
      readonly access: string;
      readonly refresh: string;
    };
    TokenPair: {
      access: string;
      refresh: string;
    };
    TokenRefresh: {
      readonly access: string;
      refresh: string;
    };
    User: {
      readonly id: number;
      /**
       * Адрес электронной почты
       * Format: email
       */
      readonly email: string;
      /** Имя */
      readonly first_name: string;
      /** Фамилия */
      readonly last_name: string;
      /** @default  */
      readonly phone: string;
      /**
       * Дата регистрации
       * Format: date-time
       */
      readonly date_joined: string;
    };
    /**
     * @description * `gold` - gold
     *     * `silver` - silver
     *     * `bronze` - bronze
     *     * `black` - black
     *     * `beige` - beige
     * @enum {string}
     */
    ZipperColorEnum: "gold" | "silver" | "bronze" | "black" | "beige";
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  auth_me_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  auth_me_partial_update: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: {
      content: {
        "application/json": components["schemas"]["PatchedProfileUpdate"];
        "application/x-www-form-urlencoded": components["schemas"]["PatchedProfileUpdate"];
        "multipart/form-data": components["schemas"]["PatchedProfileUpdate"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["User"];
        };
      };
    };
  };
  auth_password_change_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordChange"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordChange"];
        "multipart/form-data": components["schemas"]["PasswordChange"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
    };
  };
  auth_password_reset_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordReset"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordReset"];
        "multipart/form-data": components["schemas"]["PasswordReset"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
    };
  };
  auth_password_reset_confirm_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PasswordResetConfirm"];
        "application/x-www-form-urlencoded": components["schemas"]["PasswordResetConfirm"];
        "multipart/form-data": components["schemas"]["PasswordResetConfirm"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Detail"];
        };
      };
    };
  };
  auth_register_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Register"];
        "application/x-www-form-urlencoded": components["schemas"]["Register"];
        "multipart/form-data": components["schemas"]["Register"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenPair"];
        };
      };
    };
  };
  auth_token_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenObtainPair"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenObtainPair"];
        "multipart/form-data": components["schemas"]["TokenObtainPair"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenObtainPair"];
        };
      };
    };
  };
  auth_token_refresh_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TokenRefresh"];
        "application/x-www-form-urlencoded": components["schemas"]["TokenRefresh"];
        "multipart/form-data": components["schemas"]["TokenRefresh"];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TokenRefresh"];
        };
      };
    };
  };
  categories_list: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"][];
        };
      };
    };
  };
  categories_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Category"];
        };
      };
    };
  };
  health_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description No response body */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  orders_create: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["Checkout"];
        "application/x-www-form-urlencoded": components["schemas"]["Checkout"];
        "multipart/form-data": components["schemas"]["Checkout"];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["OrderRead"];
        };
      };
    };
  };
  orders_my_list: {
    parameters: {
      query?: {
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        page_size?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedOrderReadList"];
        };
      };
    };
  };
  products_list: {
    parameters: {
      query?: {
        category?: string;
        in_stock?: boolean;
        max_price?: number;
        min_price?: number;
        /** @description Which field to use when ordering the results. */
        ordering?: string;
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        page_size?: number;
        /** @description A search term. */
        search?: string;
      };
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PaginatedProductListList"];
        };
      };
    };
  };
  products_retrieve: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        slug: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["ProductDetail"];
        };
      };
    };
  };
}
