# Generated by Django 5.2.15 on 2026-07-03 20:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "Новый"),
                            ("confirmed", "Подтверждён"),
                            ("shipped", "Отправлен"),
                            ("done", "Завершён"),
                            ("cancelled", "Отменён"),
                        ],
                        default="new",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("pending", "Ожидает оплаты"),
                            ("paid", "Оплачен"),
                            ("failed", "Ошибка оплаты"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Статус оплаты",
                    ),
                ),
                ("customer_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("customer_phone", models.CharField(max_length=20, verbose_name="Телефон")),
                ("customer_email", models.EmailField(max_length=254, verbose_name="Email")),
                (
                    "comment",
                    models.TextField(blank=True, verbose_name="Комментарий (адрес, пожелания)"),
                ),
                (
                    "total",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Сумма, ₽"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создан")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлён")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("product_name", models.CharField(max_length=250, verbose_name="Название")),
                ("sku", models.CharField(blank=True, max_length=64, verbose_name="SKU")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена на момент покупки, ₽"
                    ),
                ),
                ("quantity", models.PositiveIntegerField(default=1, verbose_name="Количество")),
                (
                    "custom_config",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Конфигурация конструктора"
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                        verbose_name="Заказ",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productvariant",
                        verbose_name="Вариант товара",
                    ),
                ),
            ],
            options={
                "verbose_name": "Позиция заказа",
                "verbose_name_plural": "Позиции заказов",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("variant__isnull", False),
                            ("custom_config__isnull", False),
                            _connector="OR",
                        ),
                        name="order_item_variant_or_custom",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("quantity__gte", 1)), name="order_item_quantity_gte_1"
                    ),
                ],
            },
        ),
    ]
