# Generated by Django 5.2.15 on 2026-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_address",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="Адрес (улица, дом, кв.)"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_city",
            field=models.CharField(blank=True, max_length=150, verbose_name="Город"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_cost",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="Стоимость доставки, ₽"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("cdek_pvz", "СДЭК — пункт выдачи"),
                    ("cdek_courier", "СДЭК — курьер"),
                    ("post", "Почта России"),
                ],
                max_length=20,
                verbose_name="Способ доставки",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_postcode",
            field=models.CharField(blank=True, max_length=6, verbose_name="Индекс"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_pvz_address",
            field=models.CharField(blank=True, max_length=300, verbose_name="Адрес ПВЗ"),
        ),
        migrations.AddField(
            model_name="order",
            name="delivery_pvz_code",
            field=models.CharField(blank=True, max_length=32, verbose_name="Код ПВЗ"),
        ),
    ]
