# Generated by Django 5.2.15 on 2026-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConstructorOption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "option_type",
                    models.CharField(
                        choices=[
                            ("size", "Размер"),
                            ("bag_color", "Цвет ткани"),
                            ("zipper_color", "Цвет молнии"),
                            ("addon", "Дополнение"),
                        ],
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                ("slug", models.SlugField(verbose_name="Слаг")),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="Цена/наценка, ₽"
                    ),
                ),
                (
                    "color_hex",
                    models.CharField(blank=True, max_length=7, verbose_name="Цвет (hex)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Активна")),
                ("sort_order", models.PositiveSmallIntegerField(default=0, verbose_name="Порядок")),
            ],
            options={
                "verbose_name": "Опция конструктора",
                "verbose_name_plural": "Опции конструктора",
                "ordering": ["option_type", "sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("option_type", "slug"), name="unique_constructor_option_slug"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("price__gte", 0)), name="constructor_option_price_gte_0"
                    ),
                ],
            },
        ),
    ]
