# Generated by Django 5.2.15 on 2026-07-06 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_seed_constructor_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvariant",
            name="weight_grams",
            field=models.PositiveIntegerField(
                default=300, help_text="Для расчёта доставки", verbose_name="Вес с упаковкой, г"
            ),
        ),
    ]
