# Generated by Django 5.2.15 on 2026-07-08 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_productvariant_weight_grams"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="care",
            field=models.CharField(
                blank=True,
                help_text="Например: ручная стирка при 30°, не отжимать",
                max_length=200,
                verbose_name="Уход",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="composition",
            field=models.CharField(
                blank=True,
                help_text="Например: букле (100% хлопок), подклад — лён",
                max_length=200,
                verbose_name="Состав",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="dimensions",
            field=models.CharField(
                blank=True,
                help_text="Например: 20 × 12 × 10 см",
                max_length=120,
                verbose_name="Размеры",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="production_time",
            field=models.CharField(
                blank=True,
                help_text="Например: в наличии — отправим за 1–2 дня / пошив 3–5 рабочих дней",
                max_length=120,
                verbose_name="Срок изготовления",
            ),
        ),
    ]
